### ISSUE TITLE
Error while installing: Does administrative user have access to the database? ( No such file or directory )

### ISSUE THREAD

**Issue by mk48** [xlrl/docker-mantisbt#4] opened 2019-02-28 08:21 UTC
Below is my docker compose file
```
mantisbt:
  image: xlrl/mantisbt:latest
  ports:
    - "8989:80"
  links:
    - mysql
  volumes:
    - C:/docker/mantisbt/config:/var/lib/www/html/config
    - C:/docker/mantisbt/custom:/var/lib/www/html/custom
  restart: always

mysql:
  image: mariadb:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantisbt
    - MYSQL_PASSWORD=mantisbt
  volumes:
    - C:/docker/mantisbt/mysql:/var/lib/mysql
  restart: always
```
I am able to open http://localhost:8989/admin/install.php page

![image](https://user-images.githubusercontent.com/3082469/53551408-4362ef80-3b5f-11e9-907a-1aa246c91e97.png)

Getting that error when I click "Install/Upgrade Database" button 

I am getting below error in **docker-compose up** command window, is it the reason?

![image](https://user-images.githubusercontent.com/3082469/53551658-c6844580-3b5f-11e9-83a7-cda9454d68e4.png)

**Comment by paulosbarros** [comment] 2019-09-18 19:27
Hello :)
If anyone still having the same error, please check if you are using 'localhost' as the hostname and change it to 'mysql' as the `xlrl` mention on the readme.
I spent two days to fix that...

**Comment by XelaRellum** [comment] 2021-12-11 18:16
Did hear more so I guess the issue is fixed. Closing this.

**Closed by XelaRellum** 2021-12-11 18:16 UTC

**Comment by pkbarbiedoll** [comment] 2024-01-18 18:44
> Hello :) If anyone still having the same error, please check if you are using 'localhost' as the hostname and change it to 'mysql' as the `xlrl` mention on the readme. I spent two days to fix that...

Changing the hostname to 'mysql' did not work for me.

**Comment by XelaRellum** [comment] 2024-01-19 16:09
> > Hello :) If anyone still having the same error, please check if you are using 'localhost' as the hostname and change it to 'mysql' as the `xlrl` mention on the readme. I spent two days to fix that...
> 
> Changing the hostname to 'mysql' did not work for me.

Please screenshot the install.php page and add your docker-compose.yml (with passwords removed/grayed out)
